spring:
  application:
    name: learning-webserver
  profiles:
    include:
      - core
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus